/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:127eb495-0045-4fb1-a91c-25d1fdb0baa6",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_uRPMiS4K9",
    "aws_user_pools_web_client_id": "670om5hdmg9863k4fflt41279g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "simplecloudstorageefded4746b7146beb038662f439a310319-dev",
    "aws_user_files_s3_bucket_region": "eu-north-1",
    "aws_cloud_logic_custom": [
        {
            "name": "MakeObjectPublic",
            "endpoint": "https://3toecrirh7.execute-api.eu-north-1.amazonaws.com/staging",
            "region": "eu-north-1"
        }
    ],
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
